In [1]:
import cv2 as cv
import numpy as np

In [2]:
classifier = cv.CascadeClassifier('haarcascade_frontalface_default.xml')

cam = cv.VideoCapture(0)

while True:
    
    _, img = cam.read()
    img = cv.flip(img,1)
    
    faces = classifier.detectMultiScale(img, 1.1, 8)
    
    cv.imshow('Frame', img)
    
    print(faces)
    print('--------')
    
    if cv.waitKey(1) == 27:
        cam.release()
        break  27

[[115 298 167 167]]
--------
[[ 94 306 163 163]]
--------
[[ 93 304 167 167]]
--------
[[ 96 311 157 157]]
--------
[[ 93 309 160 160]]
--------
[[ 92 310 162 162]]
--------
[[ 90 309 164 164]]
--------
[[ 96 314 158 158]]
--------
()
--------
()
--------
()
--------
()
--------
()
--------
()
--------
()
--------
()
--------
()
--------
()
--------
()
--------
()
--------
()
--------
()
--------
()
--------
()
--------
()
--------
()
--------
()
--------
()
--------
()
--------
()
--------
()
--------
()
--------
()
--------
()
--------
()
--------
()
--------
()
--------
()
--------
()
--------
()
--------
[[ 99 314 160 160]]
--------
[[101 313 159 159]]
--------
[[103 314 159 159]]
--------
[[106 311 162 162]]
--------
[[116 312 159 159]]
--------
[[116 312 159 159]]
--------
[[122 311 158 158]]
--------
[[122 310 159 159]]
--------
[[120 308 160 160]]
--------
[[120 307 161 161]]
--------
[[119 307 161 161]]
--------
[[116 304 165 165]]
--------
[[119 306 160 160]]
--------
[[120 3

KeyboardInterrupt: 

In [ ]:
classifier = cv.CascadeClassifier('haarcascade_frontalface_default.xml')

cam = cv.VideoCapture(0)

while True:
    
    _, img = cam.read()
    img = cv.flip(img,1)
    
    
    try:
        faces = classifier.detectMultiScale(img, 1.1, 5) # 1.1 decides the frame rate in images and 5 decide acqracy of frame  
        for (x,y,w,h) in faces:
            cv.rectangle(img, (x,y),(x+w,y+h) , (0,180,0), 2)
    except:
        pass
    
     
    cv.imshow('Frame'  , img )
    
    if cv.waitKey(1) == 27:
        cam.release()
        break

### Crop Faces using Haar-Cascade

In [ ]:
list(faces)

In [ ]:
img.shape

In [ ]:
(x, x+w), (y, y+h)

In [ ]:
for i in faces:
    print(faces[0],y,w,h)

In [ ]:
faces[0]

In [ ]:
for x in faces:
    print(cord)
    print(x,y,w,h)  

In [ ]:
for face in faces:
    if face[-1] == max(faces[:,-1]):
        print(face)

In [ ]:
classifier = cv.CascadeClassifier('haarcascade_frontalface_default.xml')

cam = cv.VideoCapture(0)

while True:
    
    _, img = cam.read()
    img = cv.flip(img,1)
    
    faces = classifier.detectMultiScale(img, 1.1, 5)
    
    for f in faces:                             # Going through Each Face Detected
        if f[-1] == max(faces[:,-1]):           # Finding the Face with Maximum Area
            break 

    if (len(faces) >= 1):                       # Drawing Rectange on the Face
        x = f[0] 
        y = f[1] 
        w = f[2]
        h = f[3]

        cv.rectangle(img, (x,y),(x+w,y+h) , (0,180,0), 2)   
        face = img[y:y+h, x:x+w]
        
        face = cv.resize(face, (256,256))

    cv.imshow('Frame'  , img )
    cv.imshow('Face'   , face)
    
    if cv.waitKey(1) == 27:
        cam.release()
        break

### Blur the Face

In [ ]:
classifier = cv.CascadeClassifier('haarcascade_frontalface_default.xml')

cam = cv.VideoCapture(0)

while True:
    
    _, img = cam.read()
    img = cv.flip(img,1)
    
    faces = classifier.detectMultiScale(img, 1.1, 5)
    
    for f in faces:
        if f[-1] == max(faces[:,-1]):
            break

    if (len(faces) >= 1):
        x = f[0] 
        y = f[1] 
        w = f[2]
        h = f[3]

#         cv.rectangle(img, (x,y),(x+w,y+h) , (0,180,0), 2)   

        face = img[y:y+h, x:x+w]                 # Getting the Face Area from Video Feed
        face = cv.blur(face, (32,32))            # Applying Blur on the Face
        img[y:y+h, x:x+w] = face                 # Apply Blured Face on Video Feed
        

    cv.imshow('Frame'  , img )
    cv.imshow('Face'   , face)
    
    if cv.waitKey(1) == 27:
        cam.release()
        break

### Apply borders on Faces

#### Creating Sqaure

In [ ]:
import cv2 as cv
import numpy as np

classifier = cv.CascadeClassifier('haarcascade_frontalface_default.xml')
cam = cv.VideoCapture(0)

while True:
    
    _, img = cam.read()
    img = cv.flip(img,1)
    
    faces = classifier.detectMultiScale(img, 1.1, 5)
    
    for f in faces:
        if f[-1] == max(faces[:,-1]):
            break

    x = f[0] 
    y = f[1] 
    w = f[2]
    h = f[3]

    face = img[y:y+h, x:x+w]
    
    black = np.zeros((face.shape), dtype = int)
    
    img[y:y+h, x:x+w] = black

    cv.imshow('Frame'  , img )
    cv.imshow('Face'   , face)
    
    if cv.waitKey(1) == 27:
        cam.release()
        break

#### Create Circle

In [ ]:
import cv2 as cv
import numpy as np

classifier = cv.CascadeClassifier('haarcascade_frontalface_default.xml')
cam = cv.VideoCapture(0)

while True:
    
    _, img = cam.read()
    img = cv.flip(img,1)
    
    faces = classifier.detectMultiScale(img, 1.1, 5)
    
    for f in faces:
        if f[-1] == max(faces[:,-1]):
            break

    x = f[0] 
    y = f[1] 
    w = f[2]
    h = f[3]
    
    circle_x = x + int(w/2)
    circle_y = y + int(h/2)
    
    cv.circle(img, (circle_x, circle_y), int(w/1.7), (110,180,68),-1)

    cv.imshow('Frame'  , img )
    
    if cv.waitKey(1) == 27:
        cam.release()
        break

### Extract a Face from an Image

In [ ]:
import os
import cv2 as cv
import numpy as np

In [ ]:
#Extract single-2 image 
classifier = cv.CascadeClassifier('haarcascade_frontalface_default.xml')

img = cv.imread('group.png')
faces = classifier.detectMultiScale(img, 1.1, 5)

for (x,y,w,h) in faces:
    
    face = img[y:y+h, x:x+w]
    
    cv.imshow('Frame', img)
    cv.waitKey(0)
    cv.imshow('Face', face)
    cv.waitKey(0)

In [ ]:
img = cv.imread('group.png')

classifier = cv.CascadeClassifier('haarcascade_frontalface_default.xml')
faces = classifier.detectMultiScale(img, 1.1, 5)


def save(frame, folder_name): 
    name_img = len(os.listdir(folder_name)) + 1
    name_img = folder_name + "/IMG_" + str(name_img) + '.png'
    cv.imwrite(name_img, frame)
    print(name_img ,'is exported')


for (x,y,w,h) in faces:

    face = img[y:y+h, x:x+w]
    cv.imshow('Face'   , face)
    
    
    if cv.waitKey(0) == 13:         # Save the Image | 13  = Enter Key
        save(face, 'People')
    
    elif cv.waitKey(0) == 127:      # Skip the Image | 127 = Delete Key
        pass